//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Repeater/RepeaterKeybinds.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace NotReaper.Repeaters
{
    public partial class @RepeaterKeybinds : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @RepeaterKeybinds()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""RepeaterKeybinds"",
    ""maps"": [
        {
            ""name"": ""Repeater"",
            ""id"": ""9dda2d3e-29ab-498c-8182-556d72cdc341"",
            ""actions"": [
                {
                    ""name"": ""FlipTargetColorsOfRepeater"",
                    ""type"": ""Button"",
                    ""id"": ""13f14f12-223d-49b5-bed2-73550d614098"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MirrorTargetsHorizontally"",
                    ""type"": ""Button"",
                    ""id"": ""5c1175a3-e3be-49f4-a869-c7a2076ad223"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MirrorTargetsVertically"",
                    ""type"": ""Button"",
                    ""id"": ""3572a92c-c6a4-4152-9846-9484d43b37b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MakeRepeaterUnique"",
                    ""type"": ""Button"",
                    ""id"": ""da53d34b-1700-4948-8cd3-d23da2d0c3c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeleteRepeaterSection"",
                    ""type"": ""Button"",
                    ""id"": ""095186d0-4e99-4f9c-81e7-f7bb1bb03f9e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BakeSection"",
                    ""type"": ""Button"",
                    ""id"": ""af1f83cd-1777-45a3-93a7-a0851b4b3632"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f437dff8-c644-4586-9e8e-02f0799d684c"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlipTargetColorsOfRepeater"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc5e7658-3ea1-41a6-a642-281aacc0353b"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MirrorTargetsHorizontally"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe3bef13-0d02-4568-8590-ca34cd9abd30"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MirrorTargetsVertically"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9de3ed79-2190-4248-91fb-a439ec4ffc1d"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MakeRepeaterUnique"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecf612f5-fbf9-4683-ad19-fbdffd4c800b"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteRepeaterSection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61e88258-8a6d-403b-9a19-f77dacdb1cb2"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BakeSection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Repeater
            m_Repeater = asset.FindActionMap("Repeater", throwIfNotFound: true);
            m_Repeater_FlipTargetColorsOfRepeater = m_Repeater.FindAction("FlipTargetColorsOfRepeater", throwIfNotFound: true);
            m_Repeater_MirrorTargetsHorizontally = m_Repeater.FindAction("MirrorTargetsHorizontally", throwIfNotFound: true);
            m_Repeater_MirrorTargetsVertically = m_Repeater.FindAction("MirrorTargetsVertically", throwIfNotFound: true);
            m_Repeater_MakeRepeaterUnique = m_Repeater.FindAction("MakeRepeaterUnique", throwIfNotFound: true);
            m_Repeater_DeleteRepeaterSection = m_Repeater.FindAction("DeleteRepeaterSection", throwIfNotFound: true);
            m_Repeater_BakeSection = m_Repeater.FindAction("BakeSection", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Repeater
        private readonly InputActionMap m_Repeater;
        private IRepeaterActions m_RepeaterActionsCallbackInterface;
        private readonly InputAction m_Repeater_FlipTargetColorsOfRepeater;
        private readonly InputAction m_Repeater_MirrorTargetsHorizontally;
        private readonly InputAction m_Repeater_MirrorTargetsVertically;
        private readonly InputAction m_Repeater_MakeRepeaterUnique;
        private readonly InputAction m_Repeater_DeleteRepeaterSection;
        private readonly InputAction m_Repeater_BakeSection;
        public struct RepeaterActions
        {
            private @RepeaterKeybinds m_Wrapper;
            public RepeaterActions(@RepeaterKeybinds wrapper) { m_Wrapper = wrapper; }
            public InputAction @FlipTargetColorsOfRepeater => m_Wrapper.m_Repeater_FlipTargetColorsOfRepeater;
            public InputAction @MirrorTargetsHorizontally => m_Wrapper.m_Repeater_MirrorTargetsHorizontally;
            public InputAction @MirrorTargetsVertically => m_Wrapper.m_Repeater_MirrorTargetsVertically;
            public InputAction @MakeRepeaterUnique => m_Wrapper.m_Repeater_MakeRepeaterUnique;
            public InputAction @DeleteRepeaterSection => m_Wrapper.m_Repeater_DeleteRepeaterSection;
            public InputAction @BakeSection => m_Wrapper.m_Repeater_BakeSection;
            public InputActionMap Get() { return m_Wrapper.m_Repeater; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(RepeaterActions set) { return set.Get(); }
            public void SetCallbacks(IRepeaterActions instance)
            {
                if (m_Wrapper.m_RepeaterActionsCallbackInterface != null)
                {
                    @FlipTargetColorsOfRepeater.started -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnFlipTargetColorsOfRepeater;
                    @FlipTargetColorsOfRepeater.performed -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnFlipTargetColorsOfRepeater;
                    @FlipTargetColorsOfRepeater.canceled -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnFlipTargetColorsOfRepeater;
                    @MirrorTargetsHorizontally.started -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMirrorTargetsHorizontally;
                    @MirrorTargetsHorizontally.performed -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMirrorTargetsHorizontally;
                    @MirrorTargetsHorizontally.canceled -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMirrorTargetsHorizontally;
                    @MirrorTargetsVertically.started -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMirrorTargetsVertically;
                    @MirrorTargetsVertically.performed -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMirrorTargetsVertically;
                    @MirrorTargetsVertically.canceled -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMirrorTargetsVertically;
                    @MakeRepeaterUnique.started -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMakeRepeaterUnique;
                    @MakeRepeaterUnique.performed -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMakeRepeaterUnique;
                    @MakeRepeaterUnique.canceled -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnMakeRepeaterUnique;
                    @DeleteRepeaterSection.started -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnDeleteRepeaterSection;
                    @DeleteRepeaterSection.performed -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnDeleteRepeaterSection;
                    @DeleteRepeaterSection.canceled -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnDeleteRepeaterSection;
                    @BakeSection.started -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnBakeSection;
                    @BakeSection.performed -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnBakeSection;
                    @BakeSection.canceled -= m_Wrapper.m_RepeaterActionsCallbackInterface.OnBakeSection;
                }
                m_Wrapper.m_RepeaterActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @FlipTargetColorsOfRepeater.started += instance.OnFlipTargetColorsOfRepeater;
                    @FlipTargetColorsOfRepeater.performed += instance.OnFlipTargetColorsOfRepeater;
                    @FlipTargetColorsOfRepeater.canceled += instance.OnFlipTargetColorsOfRepeater;
                    @MirrorTargetsHorizontally.started += instance.OnMirrorTargetsHorizontally;
                    @MirrorTargetsHorizontally.performed += instance.OnMirrorTargetsHorizontally;
                    @MirrorTargetsHorizontally.canceled += instance.OnMirrorTargetsHorizontally;
                    @MirrorTargetsVertically.started += instance.OnMirrorTargetsVertically;
                    @MirrorTargetsVertically.performed += instance.OnMirrorTargetsVertically;
                    @MirrorTargetsVertically.canceled += instance.OnMirrorTargetsVertically;
                    @MakeRepeaterUnique.started += instance.OnMakeRepeaterUnique;
                    @MakeRepeaterUnique.performed += instance.OnMakeRepeaterUnique;
                    @MakeRepeaterUnique.canceled += instance.OnMakeRepeaterUnique;
                    @DeleteRepeaterSection.started += instance.OnDeleteRepeaterSection;
                    @DeleteRepeaterSection.performed += instance.OnDeleteRepeaterSection;
                    @DeleteRepeaterSection.canceled += instance.OnDeleteRepeaterSection;
                    @BakeSection.started += instance.OnBakeSection;
                    @BakeSection.performed += instance.OnBakeSection;
                    @BakeSection.canceled += instance.OnBakeSection;
                }
            }
        }
        public RepeaterActions @Repeater => new RepeaterActions(this);
        public interface IRepeaterActions
        {
            void OnFlipTargetColorsOfRepeater(InputAction.CallbackContext context);
            void OnMirrorTargetsHorizontally(InputAction.CallbackContext context);
            void OnMirrorTargetsVertically(InputAction.CallbackContext context);
            void OnMakeRepeaterUnique(InputAction.CallbackContext context);
            void OnDeleteRepeaterSection(InputAction.CallbackContext context);
            void OnBakeSection(InputAction.CallbackContext context);
        }
    }
}
