//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/HitsoundTimeline/HitsoundKeybinds.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace NotReaper.HitsoundTimeline
{
    public partial class @HitsoundKeybinds : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @HitsoundKeybinds()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""HitsoundKeybinds"",
    ""maps"": [
        {
            ""name"": ""Hitsounds"",
            ""id"": ""baf29bb7-9e2c-49df-8245-bf8cdac608dc"",
            ""actions"": [
                {
                    ""name"": ""PlaceMarker"",
                    ""type"": ""Button"",
                    ""id"": ""d9e89649-be74-433d-a52e-7b19d8a2190d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveMarker"",
                    ""type"": ""Button"",
                    ""id"": ""739e3ca2-cecf-43f1-863d-ecdaf9bf057b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeleteMarker"",
                    ""type"": ""Button"",
                    ""id"": ""68c31922-cbd7-4fd3-8144-84be83feb468"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DragSelect"",
                    ""type"": ""Button"",
                    ""id"": ""88c52d03-e8e7-46b1-8f96-f3348cffb81e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Copy"",
                    ""type"": ""Button"",
                    ""id"": ""ae9b3b21-7d5d-4f68-8699-80ac9735a7bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Redo"",
                    ""type"": ""Button"",
                    ""id"": ""63df4bdd-16fe-4fc1-b696-4cafff90954d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Button"",
                    ""id"": ""9d463d84-28e1-45ea-acec-7a60a42bfbad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAll"",
                    ""type"": ""Button"",
                    ""id"": ""5f71850e-5fcd-4de4-9cae-1350b5d17a97"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeselectAll"",
                    ""type"": ""Button"",
                    ""id"": ""1b1750c9-f10d-48f3-9c5a-4c70d2d16611"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cut"",
                    ""type"": ""Button"",
                    ""id"": ""08c666d0-c8ad-4a3b-b533-91ef3d76e9f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Paste"",
                    ""type"": ""Button"",
                    ""id"": ""05af2b02-d895-41f2-91ae-03d7d613564e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scrub"",
                    ""type"": ""Button"",
                    ""id"": ""fda1781b-747b-4b4e-9f02-8472b366aa47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveSelectedHitsoundsUp"",
                    ""type"": ""Button"",
                    ""id"": ""1d0fa2aa-b61a-4d4a-b8f8-ede27897e6b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveSelectedHitsoundsDown"",
                    ""type"": ""Button"",
                    ""id"": ""c14689ad-7936-48fa-9394-00d72e541a17"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c16abedf-4669-4935-acd9-babe07ebaac7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceMarker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88009619-e065-4bb1-b843-d20f3a474521"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveMarker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51d49691-f536-47fc-97d5-0dc30ad24436"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteMarker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dfda56f-da55-4512-9308-d0528ff6a703"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""5cef5022-11ff-4854-86c1-0a90c8ab4f19"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""46981a16-ddaf-4890-8abf-ffe23ae8bf7b"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""14e83a7f-74e1-4d92-8674-a4bfe4f2db1b"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""ae6baa6e-ee04-4c4b-897d-8f10bc02fae8"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paste"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""46d42de6-3fa6-4537-8816-6c3105c9ec6e"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""70b65330-04ac-41fe-89c5-f5cadd5ed2d8"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""ec3e2357-b69f-4fe5-8b65-89aeac31ecfe"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ceeb5954-dd91-46fd-b953-ab8cf0f81398"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""cb7511c2-c46f-4aa7-8f5a-be9634ed8dba"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""415dffd9-9ac4-442b-a35f-22c8f2f0affd"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeselectAll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""48d521fc-a6a3-4798-80d9-752f348f7db9"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeselectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""cb5640d1-d9c5-459a-a0ea-28d4ad2d5f76"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeselectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""a9e3b05c-5d3d-4269-bd0c-ac84f78df348"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f6576af9-2d4e-4d56-84f1-8e940f21ba1c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""06d5fd5b-c08a-4d2f-b4af-b91fca4179b6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""ad4ea7a0-7704-4da1-a064-d377914c92d6"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8d65a535-acee-4bd3-863e-2f32950412ae"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""c7be8580-6ef2-4c21-aa24-f1139ae2cc45"",
                    ""path"": ""<Keyboard>/#(Z)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""12607a8b-7759-47bb-88e9-d9031d0a755d"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""fc5af37c-6a26-4c2b-983d-cc3dbc19f450"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""4a024694-1467-438b-abb5-2cc336a66583"",
                    ""path"": ""<Keyboard>/#(Y)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""72c61854-c179-4491-bf9b-9fb0a5a4bc05"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scrub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""705fddd0-a241-496d-8576-6c76f8ae6cd2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSelectedHitsoundsUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2922323-089c-44c2-82f1-6d1e2a605929"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSelectedHitsoundsDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Hitsounds
            m_Hitsounds = asset.FindActionMap("Hitsounds", throwIfNotFound: true);
            m_Hitsounds_PlaceMarker = m_Hitsounds.FindAction("PlaceMarker", throwIfNotFound: true);
            m_Hitsounds_RemoveMarker = m_Hitsounds.FindAction("RemoveMarker", throwIfNotFound: true);
            m_Hitsounds_DeleteMarker = m_Hitsounds.FindAction("DeleteMarker", throwIfNotFound: true);
            m_Hitsounds_DragSelect = m_Hitsounds.FindAction("DragSelect", throwIfNotFound: true);
            m_Hitsounds_Copy = m_Hitsounds.FindAction("Copy", throwIfNotFound: true);
            m_Hitsounds_Redo = m_Hitsounds.FindAction("Redo", throwIfNotFound: true);
            m_Hitsounds_Undo = m_Hitsounds.FindAction("Undo", throwIfNotFound: true);
            m_Hitsounds_SelectAll = m_Hitsounds.FindAction("SelectAll", throwIfNotFound: true);
            m_Hitsounds_DeselectAll = m_Hitsounds.FindAction("DeselectAll", throwIfNotFound: true);
            m_Hitsounds_Cut = m_Hitsounds.FindAction("Cut", throwIfNotFound: true);
            m_Hitsounds_Paste = m_Hitsounds.FindAction("Paste", throwIfNotFound: true);
            m_Hitsounds_Scrub = m_Hitsounds.FindAction("Scrub", throwIfNotFound: true);
            m_Hitsounds_MoveSelectedHitsoundsUp = m_Hitsounds.FindAction("MoveSelectedHitsoundsUp", throwIfNotFound: true);
            m_Hitsounds_MoveSelectedHitsoundsDown = m_Hitsounds.FindAction("MoveSelectedHitsoundsDown", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Hitsounds
        private readonly InputActionMap m_Hitsounds;
        private IHitsoundsActions m_HitsoundsActionsCallbackInterface;
        private readonly InputAction m_Hitsounds_PlaceMarker;
        private readonly InputAction m_Hitsounds_RemoveMarker;
        private readonly InputAction m_Hitsounds_DeleteMarker;
        private readonly InputAction m_Hitsounds_DragSelect;
        private readonly InputAction m_Hitsounds_Copy;
        private readonly InputAction m_Hitsounds_Redo;
        private readonly InputAction m_Hitsounds_Undo;
        private readonly InputAction m_Hitsounds_SelectAll;
        private readonly InputAction m_Hitsounds_DeselectAll;
        private readonly InputAction m_Hitsounds_Cut;
        private readonly InputAction m_Hitsounds_Paste;
        private readonly InputAction m_Hitsounds_Scrub;
        private readonly InputAction m_Hitsounds_MoveSelectedHitsoundsUp;
        private readonly InputAction m_Hitsounds_MoveSelectedHitsoundsDown;
        public struct HitsoundsActions
        {
            private @HitsoundKeybinds m_Wrapper;
            public HitsoundsActions(@HitsoundKeybinds wrapper) { m_Wrapper = wrapper; }
            public InputAction @PlaceMarker => m_Wrapper.m_Hitsounds_PlaceMarker;
            public InputAction @RemoveMarker => m_Wrapper.m_Hitsounds_RemoveMarker;
            public InputAction @DeleteMarker => m_Wrapper.m_Hitsounds_DeleteMarker;
            public InputAction @DragSelect => m_Wrapper.m_Hitsounds_DragSelect;
            public InputAction @Copy => m_Wrapper.m_Hitsounds_Copy;
            public InputAction @Redo => m_Wrapper.m_Hitsounds_Redo;
            public InputAction @Undo => m_Wrapper.m_Hitsounds_Undo;
            public InputAction @SelectAll => m_Wrapper.m_Hitsounds_SelectAll;
            public InputAction @DeselectAll => m_Wrapper.m_Hitsounds_DeselectAll;
            public InputAction @Cut => m_Wrapper.m_Hitsounds_Cut;
            public InputAction @Paste => m_Wrapper.m_Hitsounds_Paste;
            public InputAction @Scrub => m_Wrapper.m_Hitsounds_Scrub;
            public InputAction @MoveSelectedHitsoundsUp => m_Wrapper.m_Hitsounds_MoveSelectedHitsoundsUp;
            public InputAction @MoveSelectedHitsoundsDown => m_Wrapper.m_Hitsounds_MoveSelectedHitsoundsDown;
            public InputActionMap Get() { return m_Wrapper.m_Hitsounds; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(HitsoundsActions set) { return set.Get(); }
            public void SetCallbacks(IHitsoundsActions instance)
            {
                if (m_Wrapper.m_HitsoundsActionsCallbackInterface != null)
                {
                    @PlaceMarker.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnPlaceMarker;
                    @PlaceMarker.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnPlaceMarker;
                    @PlaceMarker.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnPlaceMarker;
                    @RemoveMarker.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnRemoveMarker;
                    @RemoveMarker.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnRemoveMarker;
                    @RemoveMarker.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnRemoveMarker;
                    @DeleteMarker.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDeleteMarker;
                    @DeleteMarker.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDeleteMarker;
                    @DeleteMarker.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDeleteMarker;
                    @DragSelect.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDragSelect;
                    @DragSelect.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDragSelect;
                    @DragSelect.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDragSelect;
                    @Copy.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnCopy;
                    @Copy.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnCopy;
                    @Copy.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnCopy;
                    @Redo.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnRedo;
                    @Redo.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnRedo;
                    @Redo.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnRedo;
                    @Undo.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnUndo;
                    @Undo.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnUndo;
                    @Undo.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnUndo;
                    @SelectAll.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnSelectAll;
                    @SelectAll.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnSelectAll;
                    @SelectAll.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnSelectAll;
                    @DeselectAll.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDeselectAll;
                    @DeselectAll.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDeselectAll;
                    @DeselectAll.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnDeselectAll;
                    @Cut.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnCut;
                    @Cut.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnCut;
                    @Cut.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnCut;
                    @Paste.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnPaste;
                    @Paste.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnPaste;
                    @Paste.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnPaste;
                    @Scrub.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnScrub;
                    @Scrub.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnScrub;
                    @Scrub.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnScrub;
                    @MoveSelectedHitsoundsUp.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnMoveSelectedHitsoundsUp;
                    @MoveSelectedHitsoundsUp.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnMoveSelectedHitsoundsUp;
                    @MoveSelectedHitsoundsUp.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnMoveSelectedHitsoundsUp;
                    @MoveSelectedHitsoundsDown.started -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnMoveSelectedHitsoundsDown;
                    @MoveSelectedHitsoundsDown.performed -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnMoveSelectedHitsoundsDown;
                    @MoveSelectedHitsoundsDown.canceled -= m_Wrapper.m_HitsoundsActionsCallbackInterface.OnMoveSelectedHitsoundsDown;
                }
                m_Wrapper.m_HitsoundsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @PlaceMarker.started += instance.OnPlaceMarker;
                    @PlaceMarker.performed += instance.OnPlaceMarker;
                    @PlaceMarker.canceled += instance.OnPlaceMarker;
                    @RemoveMarker.started += instance.OnRemoveMarker;
                    @RemoveMarker.performed += instance.OnRemoveMarker;
                    @RemoveMarker.canceled += instance.OnRemoveMarker;
                    @DeleteMarker.started += instance.OnDeleteMarker;
                    @DeleteMarker.performed += instance.OnDeleteMarker;
                    @DeleteMarker.canceled += instance.OnDeleteMarker;
                    @DragSelect.started += instance.OnDragSelect;
                    @DragSelect.performed += instance.OnDragSelect;
                    @DragSelect.canceled += instance.OnDragSelect;
                    @Copy.started += instance.OnCopy;
                    @Copy.performed += instance.OnCopy;
                    @Copy.canceled += instance.OnCopy;
                    @Redo.started += instance.OnRedo;
                    @Redo.performed += instance.OnRedo;
                    @Redo.canceled += instance.OnRedo;
                    @Undo.started += instance.OnUndo;
                    @Undo.performed += instance.OnUndo;
                    @Undo.canceled += instance.OnUndo;
                    @SelectAll.started += instance.OnSelectAll;
                    @SelectAll.performed += instance.OnSelectAll;
                    @SelectAll.canceled += instance.OnSelectAll;
                    @DeselectAll.started += instance.OnDeselectAll;
                    @DeselectAll.performed += instance.OnDeselectAll;
                    @DeselectAll.canceled += instance.OnDeselectAll;
                    @Cut.started += instance.OnCut;
                    @Cut.performed += instance.OnCut;
                    @Cut.canceled += instance.OnCut;
                    @Paste.started += instance.OnPaste;
                    @Paste.performed += instance.OnPaste;
                    @Paste.canceled += instance.OnPaste;
                    @Scrub.started += instance.OnScrub;
                    @Scrub.performed += instance.OnScrub;
                    @Scrub.canceled += instance.OnScrub;
                    @MoveSelectedHitsoundsUp.started += instance.OnMoveSelectedHitsoundsUp;
                    @MoveSelectedHitsoundsUp.performed += instance.OnMoveSelectedHitsoundsUp;
                    @MoveSelectedHitsoundsUp.canceled += instance.OnMoveSelectedHitsoundsUp;
                    @MoveSelectedHitsoundsDown.started += instance.OnMoveSelectedHitsoundsDown;
                    @MoveSelectedHitsoundsDown.performed += instance.OnMoveSelectedHitsoundsDown;
                    @MoveSelectedHitsoundsDown.canceled += instance.OnMoveSelectedHitsoundsDown;
                }
            }
        }
        public HitsoundsActions @Hitsounds => new HitsoundsActions(this);
        public interface IHitsoundsActions
        {
            void OnPlaceMarker(InputAction.CallbackContext context);
            void OnRemoveMarker(InputAction.CallbackContext context);
            void OnDeleteMarker(InputAction.CallbackContext context);
            void OnDragSelect(InputAction.CallbackContext context);
            void OnCopy(InputAction.CallbackContext context);
            void OnRedo(InputAction.CallbackContext context);
            void OnUndo(InputAction.CallbackContext context);
            void OnSelectAll(InputAction.CallbackContext context);
            void OnDeselectAll(InputAction.CallbackContext context);
            void OnCut(InputAction.CallbackContext context);
            void OnPaste(InputAction.CallbackContext context);
            void OnScrub(InputAction.CallbackContext context);
            void OnMoveSelectedHitsoundsUp(InputAction.CallbackContext context);
            void OnMoveSelectedHitsoundsDown(InputAction.CallbackContext context);
        }
    }
}
