//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/BPM/BPMDragKeybinds.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace NotReaper.BpmAlign
{
    public partial class @BPMDragKeybinds : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @BPMDragKeybinds()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""BPMDragKeybinds"",
    ""maps"": [
        {
            ""name"": ""DragAlign"",
            ""id"": ""ddbcff6b-5adf-4f20-a9d1-8813dbe0ec95"",
            ""actions"": [
                {
                    ""name"": ""TogglePlay"",
                    ""type"": ""Button"",
                    ""id"": ""d9f862b1-a276-4a69-8094-3105a3441bc3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scrub"",
                    ""type"": ""Button"",
                    ""id"": ""047afbe3-5b38-487d-a2df-10784f6b0985"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1e08ad7-3ba0-405b-8e6c-eb3fb8099be7"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TogglePlay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""154eed44-aa70-44bb-bebb-8eecb36d9266"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scrub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // DragAlign
            m_DragAlign = asset.FindActionMap("DragAlign", throwIfNotFound: true);
            m_DragAlign_TogglePlay = m_DragAlign.FindAction("TogglePlay", throwIfNotFound: true);
            m_DragAlign_Scrub = m_DragAlign.FindAction("Scrub", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // DragAlign
        private readonly InputActionMap m_DragAlign;
        private IDragAlignActions m_DragAlignActionsCallbackInterface;
        private readonly InputAction m_DragAlign_TogglePlay;
        private readonly InputAction m_DragAlign_Scrub;
        public struct DragAlignActions
        {
            private @BPMDragKeybinds m_Wrapper;
            public DragAlignActions(@BPMDragKeybinds wrapper) { m_Wrapper = wrapper; }
            public InputAction @TogglePlay => m_Wrapper.m_DragAlign_TogglePlay;
            public InputAction @Scrub => m_Wrapper.m_DragAlign_Scrub;
            public InputActionMap Get() { return m_Wrapper.m_DragAlign; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DragAlignActions set) { return set.Get(); }
            public void SetCallbacks(IDragAlignActions instance)
            {
                if (m_Wrapper.m_DragAlignActionsCallbackInterface != null)
                {
                    @TogglePlay.started -= m_Wrapper.m_DragAlignActionsCallbackInterface.OnTogglePlay;
                    @TogglePlay.performed -= m_Wrapper.m_DragAlignActionsCallbackInterface.OnTogglePlay;
                    @TogglePlay.canceled -= m_Wrapper.m_DragAlignActionsCallbackInterface.OnTogglePlay;
                    @Scrub.started -= m_Wrapper.m_DragAlignActionsCallbackInterface.OnScrub;
                    @Scrub.performed -= m_Wrapper.m_DragAlignActionsCallbackInterface.OnScrub;
                    @Scrub.canceled -= m_Wrapper.m_DragAlignActionsCallbackInterface.OnScrub;
                }
                m_Wrapper.m_DragAlignActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @TogglePlay.started += instance.OnTogglePlay;
                    @TogglePlay.performed += instance.OnTogglePlay;
                    @TogglePlay.canceled += instance.OnTogglePlay;
                    @Scrub.started += instance.OnScrub;
                    @Scrub.performed += instance.OnScrub;
                    @Scrub.canceled += instance.OnScrub;
                }
            }
        }
        public DragAlignActions @DragAlign => new DragAlignActions(this);
        public interface IDragAlignActions
        {
            void OnTogglePlay(InputAction.CallbackContext context);
            void OnScrub(InputAction.CallbackContext context);
        }
    }
}
