//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/SustainTimeline/SustainKeybinds.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace NotReaper.SustainTimeline
{
    public partial class @SustainKeybinds : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @SustainKeybinds()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""SustainKeybinds"",
    ""maps"": [
        {
            ""name"": ""Sustains"",
            ""id"": ""18ffb8eb-1e2f-42b0-8a50-955d975980cd"",
            ""actions"": [
                {
                    ""name"": ""DragSelect"",
                    ""type"": ""Button"",
                    ""id"": ""252d3f3b-1b84-4dbd-9654-0b251d153596"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Copy"",
                    ""type"": ""Button"",
                    ""id"": ""5a3613eb-cf20-432d-b74b-4017bf1762b9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Paste"",
                    ""type"": ""Button"",
                    ""id"": ""e08464e4-9459-4d7d-b59d-7b44ffde7fbc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cut"",
                    ""type"": ""Button"",
                    ""id"": ""841a23da-9767-41e4-bd29-17ef1b2c478d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeselectAll"",
                    ""type"": ""Button"",
                    ""id"": ""213cff96-94c9-4cdb-a401-d4386b702206"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectAll"",
                    ""type"": ""Button"",
                    ""id"": ""33246b53-5be0-4d36-bf7f-f8ce9814ae8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Undo"",
                    ""type"": ""Button"",
                    ""id"": ""00b36a0e-a41d-4700-a623-8b13402ac72c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Redo"",
                    ""type"": ""Button"",
                    ""id"": ""8c45a169-7fa0-4eae-bf46-feb4b3babe16"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouseClick"",
                    ""type"": ""Button"",
                    ""id"": ""709954c1-2ea0-46e5-a703-e14eacb1c76b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Delete"",
                    ""type"": ""Button"",
                    ""id"": ""fe99a376-5087-4f17-8cf2-9fff7b1cd4e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveSustain"",
                    ""type"": ""Button"",
                    ""id"": ""cfb3cb6c-f4b4-40f1-9e2d-98c85950eb06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scrub"",
                    ""type"": ""Button"",
                    ""id"": ""7f009e4e-5e95-42d3-a2e8-9a9b1545d5bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveTracksDown"",
                    ""type"": ""Button"",
                    ""id"": ""4ed6048e-3cea-4150-9317-00bfe02f9b48"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveTracksUp"",
                    ""type"": ""Button"",
                    ""id"": ""cd89be4b-8d5b-4744-bce7-646817b1ace0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""77be5306-485a-4bef-8163-a18cbb3247b3"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""4685d0d2-711a-49a7-bef3-03f0a1e8b07d"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1cd2092b-c47e-424b-9c0f-778536a473e0"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""83d41de5-8256-4520-964d-4c546779b30d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Copy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""8ea0c742-0d85-414e-96f1-d389bb2acc69"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paste"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7e8227ea-87a1-462c-a4eb-96e9e75f70de"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""fce3b916-124b-4446-b57d-6b916dc88ba0"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paste"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""716046f3-2a5e-4b40-8504-2bc0f1d5e395"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""c7bf02ed-ba22-4e36-8de2-88843ceefbe6"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""8e588ddf-cf72-4e58-a2aa-e44fd474d8c6"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""89ba3f7e-cc18-4f4d-afa4-f17e389794be"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeselectAll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""09a8b569-5a87-431d-b1d1-8eea4fc7ae2d"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeselectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""008a7a58-8aa5-4013-b821-46078f31e7b7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeselectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""19180570-eff9-47c5-b995-8333a7d692bd"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""2998fd39-34aa-4861-8531-2573cab1ad1a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""41575cf4-75f8-4db1-b957-1f178f397a18"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""17cc54c2-dc06-4c95-ba80-821afd573ca5"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8921d339-0756-4341-b1b7-98c0593492c9"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""a5831963-6e18-4cf2-b700-46f294b6adf2"",
                    ""path"": ""<Keyboard>/#(Z)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Undo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""419f44d8-6a45-449f-9f18-db06ae8ba9a6"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e9a099a2-6e11-468b-a0ac-3b9bbe5fa36e"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""button"",
                    ""id"": ""2a39e24f-115b-42ae-bf24-a28b1d598038"",
                    ""path"": ""<Keyboard>/#(Y)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Redo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5a9521ea-0ee5-4e7d-bbcc-b76c91ca21e4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""328aebfe-e953-4f2d-a859-c3023208ebbe"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcedaf32-e85e-4b78-9256-f54ae5dec14c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveSustain"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bd15dd8-1410-4fc1-9c6e-10b37b189715"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scrub"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5e9c8ec-0980-4347-adf8-6676ec2e4ebb"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveTracksDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5ce941f-f7aa-45b3-87a6-5b0b1364f0cf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveTracksUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Sustains
            m_Sustains = asset.FindActionMap("Sustains", throwIfNotFound: true);
            m_Sustains_DragSelect = m_Sustains.FindAction("DragSelect", throwIfNotFound: true);
            m_Sustains_Copy = m_Sustains.FindAction("Copy", throwIfNotFound: true);
            m_Sustains_Paste = m_Sustains.FindAction("Paste", throwIfNotFound: true);
            m_Sustains_Cut = m_Sustains.FindAction("Cut", throwIfNotFound: true);
            m_Sustains_DeselectAll = m_Sustains.FindAction("DeselectAll", throwIfNotFound: true);
            m_Sustains_SelectAll = m_Sustains.FindAction("SelectAll", throwIfNotFound: true);
            m_Sustains_Undo = m_Sustains.FindAction("Undo", throwIfNotFound: true);
            m_Sustains_Redo = m_Sustains.FindAction("Redo", throwIfNotFound: true);
            m_Sustains_LeftMouseClick = m_Sustains.FindAction("LeftMouseClick", throwIfNotFound: true);
            m_Sustains_Delete = m_Sustains.FindAction("Delete", throwIfNotFound: true);
            m_Sustains_RemoveSustain = m_Sustains.FindAction("RemoveSustain", throwIfNotFound: true);
            m_Sustains_Scrub = m_Sustains.FindAction("Scrub", throwIfNotFound: true);
            m_Sustains_MoveTracksDown = m_Sustains.FindAction("MoveTracksDown", throwIfNotFound: true);
            m_Sustains_MoveTracksUp = m_Sustains.FindAction("MoveTracksUp", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Sustains
        private readonly InputActionMap m_Sustains;
        private ISustainsActions m_SustainsActionsCallbackInterface;
        private readonly InputAction m_Sustains_DragSelect;
        private readonly InputAction m_Sustains_Copy;
        private readonly InputAction m_Sustains_Paste;
        private readonly InputAction m_Sustains_Cut;
        private readonly InputAction m_Sustains_DeselectAll;
        private readonly InputAction m_Sustains_SelectAll;
        private readonly InputAction m_Sustains_Undo;
        private readonly InputAction m_Sustains_Redo;
        private readonly InputAction m_Sustains_LeftMouseClick;
        private readonly InputAction m_Sustains_Delete;
        private readonly InputAction m_Sustains_RemoveSustain;
        private readonly InputAction m_Sustains_Scrub;
        private readonly InputAction m_Sustains_MoveTracksDown;
        private readonly InputAction m_Sustains_MoveTracksUp;
        public struct SustainsActions
        {
            private @SustainKeybinds m_Wrapper;
            public SustainsActions(@SustainKeybinds wrapper) { m_Wrapper = wrapper; }
            public InputAction @DragSelect => m_Wrapper.m_Sustains_DragSelect;
            public InputAction @Copy => m_Wrapper.m_Sustains_Copy;
            public InputAction @Paste => m_Wrapper.m_Sustains_Paste;
            public InputAction @Cut => m_Wrapper.m_Sustains_Cut;
            public InputAction @DeselectAll => m_Wrapper.m_Sustains_DeselectAll;
            public InputAction @SelectAll => m_Wrapper.m_Sustains_SelectAll;
            public InputAction @Undo => m_Wrapper.m_Sustains_Undo;
            public InputAction @Redo => m_Wrapper.m_Sustains_Redo;
            public InputAction @LeftMouseClick => m_Wrapper.m_Sustains_LeftMouseClick;
            public InputAction @Delete => m_Wrapper.m_Sustains_Delete;
            public InputAction @RemoveSustain => m_Wrapper.m_Sustains_RemoveSustain;
            public InputAction @Scrub => m_Wrapper.m_Sustains_Scrub;
            public InputAction @MoveTracksDown => m_Wrapper.m_Sustains_MoveTracksDown;
            public InputAction @MoveTracksUp => m_Wrapper.m_Sustains_MoveTracksUp;
            public InputActionMap Get() { return m_Wrapper.m_Sustains; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SustainsActions set) { return set.Get(); }
            public void SetCallbacks(ISustainsActions instance)
            {
                if (m_Wrapper.m_SustainsActionsCallbackInterface != null)
                {
                    @DragSelect.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDragSelect;
                    @DragSelect.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDragSelect;
                    @DragSelect.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDragSelect;
                    @Copy.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnCopy;
                    @Copy.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnCopy;
                    @Copy.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnCopy;
                    @Paste.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnPaste;
                    @Paste.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnPaste;
                    @Paste.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnPaste;
                    @Cut.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnCut;
                    @Cut.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnCut;
                    @Cut.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnCut;
                    @DeselectAll.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDeselectAll;
                    @DeselectAll.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDeselectAll;
                    @DeselectAll.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDeselectAll;
                    @SelectAll.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnSelectAll;
                    @SelectAll.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnSelectAll;
                    @SelectAll.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnSelectAll;
                    @Undo.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnUndo;
                    @Undo.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnUndo;
                    @Undo.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnUndo;
                    @Redo.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnRedo;
                    @Redo.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnRedo;
                    @Redo.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnRedo;
                    @LeftMouseClick.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnLeftMouseClick;
                    @LeftMouseClick.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnLeftMouseClick;
                    @LeftMouseClick.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnLeftMouseClick;
                    @Delete.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDelete;
                    @Delete.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDelete;
                    @Delete.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnDelete;
                    @RemoveSustain.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnRemoveSustain;
                    @RemoveSustain.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnRemoveSustain;
                    @RemoveSustain.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnRemoveSustain;
                    @Scrub.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnScrub;
                    @Scrub.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnScrub;
                    @Scrub.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnScrub;
                    @MoveTracksDown.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnMoveTracksDown;
                    @MoveTracksDown.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnMoveTracksDown;
                    @MoveTracksDown.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnMoveTracksDown;
                    @MoveTracksUp.started -= m_Wrapper.m_SustainsActionsCallbackInterface.OnMoveTracksUp;
                    @MoveTracksUp.performed -= m_Wrapper.m_SustainsActionsCallbackInterface.OnMoveTracksUp;
                    @MoveTracksUp.canceled -= m_Wrapper.m_SustainsActionsCallbackInterface.OnMoveTracksUp;
                }
                m_Wrapper.m_SustainsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @DragSelect.started += instance.OnDragSelect;
                    @DragSelect.performed += instance.OnDragSelect;
                    @DragSelect.canceled += instance.OnDragSelect;
                    @Copy.started += instance.OnCopy;
                    @Copy.performed += instance.OnCopy;
                    @Copy.canceled += instance.OnCopy;
                    @Paste.started += instance.OnPaste;
                    @Paste.performed += instance.OnPaste;
                    @Paste.canceled += instance.OnPaste;
                    @Cut.started += instance.OnCut;
                    @Cut.performed += instance.OnCut;
                    @Cut.canceled += instance.OnCut;
                    @DeselectAll.started += instance.OnDeselectAll;
                    @DeselectAll.performed += instance.OnDeselectAll;
                    @DeselectAll.canceled += instance.OnDeselectAll;
                    @SelectAll.started += instance.OnSelectAll;
                    @SelectAll.performed += instance.OnSelectAll;
                    @SelectAll.canceled += instance.OnSelectAll;
                    @Undo.started += instance.OnUndo;
                    @Undo.performed += instance.OnUndo;
                    @Undo.canceled += instance.OnUndo;
                    @Redo.started += instance.OnRedo;
                    @Redo.performed += instance.OnRedo;
                    @Redo.canceled += instance.OnRedo;
                    @LeftMouseClick.started += instance.OnLeftMouseClick;
                    @LeftMouseClick.performed += instance.OnLeftMouseClick;
                    @LeftMouseClick.canceled += instance.OnLeftMouseClick;
                    @Delete.started += instance.OnDelete;
                    @Delete.performed += instance.OnDelete;
                    @Delete.canceled += instance.OnDelete;
                    @RemoveSustain.started += instance.OnRemoveSustain;
                    @RemoveSustain.performed += instance.OnRemoveSustain;
                    @RemoveSustain.canceled += instance.OnRemoveSustain;
                    @Scrub.started += instance.OnScrub;
                    @Scrub.performed += instance.OnScrub;
                    @Scrub.canceled += instance.OnScrub;
                    @MoveTracksDown.started += instance.OnMoveTracksDown;
                    @MoveTracksDown.performed += instance.OnMoveTracksDown;
                    @MoveTracksDown.canceled += instance.OnMoveTracksDown;
                    @MoveTracksUp.started += instance.OnMoveTracksUp;
                    @MoveTracksUp.performed += instance.OnMoveTracksUp;
                    @MoveTracksUp.canceled += instance.OnMoveTracksUp;
                }
            }
        }
        public SustainsActions @Sustains => new SustainsActions(this);
        public interface ISustainsActions
        {
            void OnDragSelect(InputAction.CallbackContext context);
            void OnCopy(InputAction.CallbackContext context);
            void OnPaste(InputAction.CallbackContext context);
            void OnCut(InputAction.CallbackContext context);
            void OnDeselectAll(InputAction.CallbackContext context);
            void OnSelectAll(InputAction.CallbackContext context);
            void OnUndo(InputAction.CallbackContext context);
            void OnRedo(InputAction.CallbackContext context);
            void OnLeftMouseClick(InputAction.CallbackContext context);
            void OnDelete(InputAction.CallbackContext context);
            void OnRemoveSustain(InputAction.CallbackContext context);
            void OnScrub(InputAction.CallbackContext context);
            void OnMoveTracksDown(InputAction.CallbackContext context);
            void OnMoveTracksUp(InputAction.CallbackContext context);
        }
    }
}
