//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/UserInput/SpacingSnapper/SpacingSnapKeybinds.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace NotReaper.Tools.SpacingSnap
{
    public partial class @SpacingSnapKeybinds : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @SpacingSnapKeybinds()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""SpacingSnapKeybinds"",
    ""maps"": [
        {
            ""name"": ""SpacingSnap"",
            ""id"": ""a35eea9c-ccc6-4c55-aaaf-50fc4e181a1b"",
            ""actions"": [
                {
                    ""name"": ""ChangeDistance"",
                    ""type"": ""Button"",
                    ""id"": ""8d243a74-6996-426e-a405-cd27f4ad5da5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LockDirectional"",
                    ""type"": ""Button"",
                    ""id"": ""57bcaabe-8d38-49e8-83ee-a1dafe17b83f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""b281825d-919d-4a7a-aafe-8d106bf512e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Tab"",
                    ""type"": ""Button"",
                    ""id"": ""b168a2e4-7805-4ac6-a3d0-0c93e51073b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchTargetColor"",
                    ""type"": ""Button"",
                    ""id"": ""4c8afe01-7472-40e0-82db-60381dafe0fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleDistanceMode"",
                    ""type"": ""Button"",
                    ""id"": ""70390c0e-9fae-44d0-bd75-dccee93df2a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleSnapTarget"",
                    ""type"": ""Button"",
                    ""id"": ""298d178a-1ad2-47cf-8126-1caee0b4a967"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""4edc917d-6ffe-4842-9b9c-4dfae54b7c7c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDistance"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""0edd9d75-5460-44e0-a259-14f20bc132fa"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDistance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7f199965-ff16-453e-9c45-9bdc1226c7fa"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeDistance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""8979f8f7-3202-4902-8fbc-58ee4b3fa067"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockDirectional"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""dc13dff7-9c97-4c9e-a77e-c730b1e282be"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockDirectional"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""f6b53c20-eeee-416e-8374-fd50b2323ff4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LockDirectional"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""dbe6f6a6-3d15-44be-bbc6-17c746d6ab6f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edc4af85-d7bb-411d-8e12-1450fd92d4aa"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""be733ce1-051f-4db7-95c6-b6c3cfa839d4"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchTargetColor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d306366d-02a3-4798-b239-2505e0775188"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchTargetColor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ef2ccb6e-9499-43c6-9968-5f2517768967"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchTargetColor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""2957e871-e21d-407b-9552-1743727c2f90"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDistanceMode"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ed41fe7b-a2e3-4932-bc78-aad3d9ca892b"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDistanceMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""1740c0b6-e940-4a68-9e9e-aef7513f7770"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleDistanceMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""9feb81d0-916d-4098-b9af-686e2e05c286"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleSnapTarget"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f29e764d-043e-4850-b4a0-ed33d8895b9d"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleSnapTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7946a1d9-d8d8-4ec8-b03b-3a0412c531f3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleSnapTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // SpacingSnap
            m_SpacingSnap = asset.FindActionMap("SpacingSnap", throwIfNotFound: true);
            m_SpacingSnap_ChangeDistance = m_SpacingSnap.FindAction("ChangeDistance", throwIfNotFound: true);
            m_SpacingSnap_LockDirectional = m_SpacingSnap.FindAction("LockDirectional", throwIfNotFound: true);
            m_SpacingSnap_MousePosition = m_SpacingSnap.FindAction("MousePosition", throwIfNotFound: true);
            m_SpacingSnap_Tab = m_SpacingSnap.FindAction("Tab", throwIfNotFound: true);
            m_SpacingSnap_SwitchTargetColor = m_SpacingSnap.FindAction("SwitchTargetColor", throwIfNotFound: true);
            m_SpacingSnap_ToggleDistanceMode = m_SpacingSnap.FindAction("ToggleDistanceMode", throwIfNotFound: true);
            m_SpacingSnap_ToggleSnapTarget = m_SpacingSnap.FindAction("ToggleSnapTarget", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // SpacingSnap
        private readonly InputActionMap m_SpacingSnap;
        private ISpacingSnapActions m_SpacingSnapActionsCallbackInterface;
        private readonly InputAction m_SpacingSnap_ChangeDistance;
        private readonly InputAction m_SpacingSnap_LockDirectional;
        private readonly InputAction m_SpacingSnap_MousePosition;
        private readonly InputAction m_SpacingSnap_Tab;
        private readonly InputAction m_SpacingSnap_SwitchTargetColor;
        private readonly InputAction m_SpacingSnap_ToggleDistanceMode;
        private readonly InputAction m_SpacingSnap_ToggleSnapTarget;
        public struct SpacingSnapActions
        {
            private @SpacingSnapKeybinds m_Wrapper;
            public SpacingSnapActions(@SpacingSnapKeybinds wrapper) { m_Wrapper = wrapper; }
            public InputAction @ChangeDistance => m_Wrapper.m_SpacingSnap_ChangeDistance;
            public InputAction @LockDirectional => m_Wrapper.m_SpacingSnap_LockDirectional;
            public InputAction @MousePosition => m_Wrapper.m_SpacingSnap_MousePosition;
            public InputAction @Tab => m_Wrapper.m_SpacingSnap_Tab;
            public InputAction @SwitchTargetColor => m_Wrapper.m_SpacingSnap_SwitchTargetColor;
            public InputAction @ToggleDistanceMode => m_Wrapper.m_SpacingSnap_ToggleDistanceMode;
            public InputAction @ToggleSnapTarget => m_Wrapper.m_SpacingSnap_ToggleSnapTarget;
            public InputActionMap Get() { return m_Wrapper.m_SpacingSnap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SpacingSnapActions set) { return set.Get(); }
            public void SetCallbacks(ISpacingSnapActions instance)
            {
                if (m_Wrapper.m_SpacingSnapActionsCallbackInterface != null)
                {
                    @ChangeDistance.started -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnChangeDistance;
                    @ChangeDistance.performed -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnChangeDistance;
                    @ChangeDistance.canceled -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnChangeDistance;
                    @LockDirectional.started -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnLockDirectional;
                    @LockDirectional.performed -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnLockDirectional;
                    @LockDirectional.canceled -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnLockDirectional;
                    @MousePosition.started -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnMousePosition;
                    @MousePosition.performed -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnMousePosition;
                    @MousePosition.canceled -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnMousePosition;
                    @Tab.started -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnTab;
                    @Tab.performed -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnTab;
                    @Tab.canceled -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnTab;
                    @SwitchTargetColor.started -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnSwitchTargetColor;
                    @SwitchTargetColor.performed -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnSwitchTargetColor;
                    @SwitchTargetColor.canceled -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnSwitchTargetColor;
                    @ToggleDistanceMode.started -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnToggleDistanceMode;
                    @ToggleDistanceMode.performed -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnToggleDistanceMode;
                    @ToggleDistanceMode.canceled -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnToggleDistanceMode;
                    @ToggleSnapTarget.started -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnToggleSnapTarget;
                    @ToggleSnapTarget.performed -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnToggleSnapTarget;
                    @ToggleSnapTarget.canceled -= m_Wrapper.m_SpacingSnapActionsCallbackInterface.OnToggleSnapTarget;
                }
                m_Wrapper.m_SpacingSnapActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ChangeDistance.started += instance.OnChangeDistance;
                    @ChangeDistance.performed += instance.OnChangeDistance;
                    @ChangeDistance.canceled += instance.OnChangeDistance;
                    @LockDirectional.started += instance.OnLockDirectional;
                    @LockDirectional.performed += instance.OnLockDirectional;
                    @LockDirectional.canceled += instance.OnLockDirectional;
                    @MousePosition.started += instance.OnMousePosition;
                    @MousePosition.performed += instance.OnMousePosition;
                    @MousePosition.canceled += instance.OnMousePosition;
                    @Tab.started += instance.OnTab;
                    @Tab.performed += instance.OnTab;
                    @Tab.canceled += instance.OnTab;
                    @SwitchTargetColor.started += instance.OnSwitchTargetColor;
                    @SwitchTargetColor.performed += instance.OnSwitchTargetColor;
                    @SwitchTargetColor.canceled += instance.OnSwitchTargetColor;
                    @ToggleDistanceMode.started += instance.OnToggleDistanceMode;
                    @ToggleDistanceMode.performed += instance.OnToggleDistanceMode;
                    @ToggleDistanceMode.canceled += instance.OnToggleDistanceMode;
                    @ToggleSnapTarget.started += instance.OnToggleSnapTarget;
                    @ToggleSnapTarget.performed += instance.OnToggleSnapTarget;
                    @ToggleSnapTarget.canceled += instance.OnToggleSnapTarget;
                }
            }
        }
        public SpacingSnapActions @SpacingSnap => new SpacingSnapActions(this);
        public interface ISpacingSnapActions
        {
            void OnChangeDistance(InputAction.CallbackContext context);
            void OnLockDirectional(InputAction.CallbackContext context);
            void OnMousePosition(InputAction.CallbackContext context);
            void OnTab(InputAction.CallbackContext context);
            void OnSwitchTargetColor(InputAction.CallbackContext context);
            void OnToggleDistanceMode(InputAction.CallbackContext context);
            void OnToggleSnapTarget(InputAction.CallbackContext context);
        }
    }
}
